#!/bin/sh
vasm6502_oldstyle -L applesoft.lst -Fbin -o applesoft.bin applesoft.s
vasm6502_oldstyle -L mon.lst -dotdir -Fbin -o mon.bin mon.S
vasm6502_oldstyle -L mon2.lst -Fbin -o mon2.bin mon2.s
cat applesoft.bin mon2.bin > apple2plus.bin
